name: 'CM Commit tagger'
author: 'Urothis'
description: 'Tag commit with a given version'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  tag:
    description: 'Tag text'
    default: '0.1.0'
  commit-sha:
    description: optional commit sha to apply the tag to
runs:
  using: 'node16'
  main: 'lib/main.js'
